### ISSUE TITLE
No stats are being returned since Feb 9th 2021

### ISSUE THREAD

**Issue by calisaurus** [connected-web/boardgames-api#60]
On this endpoint: https://boardgames-api.calisaurus.net/api/boardgame/stats/byYear/2021, it states that
`coOpGamesPlayedCount: 8,
coOpGamesPlayedPercentage: 0.1111,
coOpGameWins: 7,
coOpGameLoses: 1,`

However on the Google spreadsheet, there are 10 co-op plays, 8 wins and 2 losses. It appears that the latest two co-op plays are being missed (`Aeon's End, 1 loss, 1 win`)

Note: The issue might also be occurring for the plays since Aeon's End and now (2 games of Scythe, 1 win for Hannah, 1 win for John) - I'll investigate.

**Comment by calisaurus** [comment]
As expected, only 16 games are being returned for the current month, whereas in reality 35 games have been played. 

Looking at the `byMonth/2021-02` endpoint, the last successfully returned game was on the 9th of Feb.

Renaming this issue to reflect this new information.

**Comment by johnbeech** [comment]
Should be resolved now; no data was being downloaded from the 2021 spreadsheet due to a bug I introduced in connected-web/google-spreadsheet-to-json#v2.0.1 which I have fixed in v2.0.2. Updated local data in repo; haven't tested the update issue workflow but it all seemed fine on the local run which uses the same credentials.
